import {test,expect} from '@playwright/test';import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';
const appURL=pathToFileURL(path.resolve('dist/cellprint.html')).href;
const demo=JSON.parse(fs.readFileSync('fixtures/synthetic.ipynb','utf8'));
const ready=page=>expect(page.locator('#cells input')).toHaveCount(6);
async function open(page){await page.goto(appURL);await ready(page);}
async function save(page,button,destination){const event=page.waitForEvent('download');await page.locator(button).click();const file=await event;await file.saveAs(destination);return fs.readFileSync(destination);}
test('actual offline downloads preserve selected sources; A4 and Letter print PDFs',async({page,context},info)=>{
 const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));context.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url());});await context.setOffline(true);await open(page);await page.locator('#build').click();await expect(page.locator('#html-download')).toBeEnabled();
 await page.screenshot({path:info.outputPath('desktop-ja.png'),fullPage:true});await page.locator('#language').click();await expect(page.locator('h1')).toContainText('Pick cells');await page.screenshot({path:info.outputPath('desktop-en.png'),fullPage:true});
 const htmlPath=info.outputPath('cellprint-source.html'),ipynbPath=info.outputPath('cellprint-excerpt.ipynb');const html=await save(page,'#html-download',htmlPath);await save(page,'#ipynb-download',ipynbPath);const repeated=await save(page,'#html-download',info.outputPath('repeated.html'));expect(repeated.equals(html)).toBeTruthy();
 const notebook=JSON.parse(fs.readFileSync(ipynbPath,'utf8'));expect(notebook.cells.map(c=>c.id)).toEqual(['nested-python','tabs-python','long-python']);for(const c of notebook.cells){const src=demo.cells.find(x=>x.id===c.id).source;expect(c.source).toBe(Array.isArray(src)?src.join(''):src);expect(c.outputs).toEqual([]);}
 for(const marker of ['UNSELECTED_','OUTPUT_','METADATA_MUST_NOT_SHIP','MARKDOWN_MUST_NOT_SHIP']){expect(html.toString()).not.toContain(marker);expect(JSON.stringify(notebook)).not.toContain(marker);}
 const printPage=await context.newPage();await printPage.goto(pathToFileURL(htmlPath).href);expect(await printPage.locator('script,iframe,object,img,link').count()).toBe(0);expect(await printPage.locator('pre code').allTextContents()).toEqual(notebook.cells.map(c=>c.source));expect(await printPage.evaluate(()=>window.BAD)).toBeUndefined();
 await printPage.emulateMedia({media:'print'});for(const format of ['A4','Letter']){await printPage.pdf({path:info.outputPath(`selected-${format}.pdf`),format,printBackground:true,preferCSSPageSize:false});}await printPage.close();
 await page.setViewportSize({width:390,height:844});await page.locator('#language').click();await page.screenshot({path:info.outputPath('mobile-ja.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await page.setViewportSize({width:1280,height:900});await page.addStyleTag({content:':root{font-size:200%}body,button,label,p,h1,h2,small,strong,summary{font-size:inherit!important}'});await page.screenshot({path:info.outputPath('enlarged-text-ja.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 expect(errors).toEqual([]);expect(external).toEqual([]);
});
test('keyboard selection invalidates downloads; rejects malformed files and bounds without echo',async({page})=>{await open(page);await page.locator('#reset').focus();await page.keyboard.press('Shift+Tab');await expect(page.locator('#choose')).toBeFocused();expect(await page.locator('#choose').evaluate(e=>e.matches(':focus-visible'))).toBeTruthy();await page.locator('#language').click();await page.locator('#build').click();await expect(page.locator('#html-download')).toBeEnabled();const box=page.locator('input[data-id="tabs-python"]');await box.focus();await page.keyboard.press('Space');await expect(box).not.toBeChecked();await expect(page.locator('#html-download')).toBeDisabled();await expect(page.locator('#result')).toBeHidden();
 const malformed=structuredClone(demo);malformed.cells[3].id=malformed.cells[2].id;await page.locator('#file').setInputFiles({name:'duplicate.ipynb',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(malformed))});await expect(page.locator('#status')).toContainText('Import failed');await expect(page.locator('#html-download')).toBeDisabled();await ready(page);
 await expect(page.locator('#file')).toHaveValue('');await page.locator('#file').setInputFiles({name:'duplicate.ipynb',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(demo))});await expect(page.locator('#file-name')).toHaveText('duplicate.ipynb');await expect(page.locator('#cells input:checked')).toHaveCount(0);await expect(page.locator('#file')).toHaveValue('');
 const invalidBytes=Buffer.from(JSON.stringify(demo));invalidBytes[invalidBytes.indexOf('CP_FIRST_SELECTED')]=0xff;await page.locator('#file').setInputFiles({name:'utf8.ipynb',mimeType:'application/json',buffer:invalidBytes});await expect(page.locator('#status')).toContainText('Import failed');
 await page.locator('#file').setInputFiles({name:'bom.ipynb',mimeType:'application/json',buffer:Buffer.concat([Buffer.from([0xef,0xbb,0xbf]),Buffer.from(JSON.stringify(demo))])});await expect(page.locator('#file-name')).toHaveText('bom.ipynb');await expect(page.locator('#cells input:checked')).toHaveCount(0);
 await page.locator('#file').setInputFiles({name:'invalid.ipynb',mimeType:'application/json',buffer:Buffer.from('{PRIVATE_PARSE_ERROR_SENTINEL')});await expect(page.locator('#status')).toContainText('Import failed');expect(await page.locator('body').textContent()).not.toContain('PRIVATE_PARSE_ERROR_SENTINEL');
 await page.locator('#file').setInputFiles({name:'large.ipynb',mimeType:'application/json',buffer:Buffer.alloc(20*1024*1024+1,32)});await expect(page.locator('#status')).toContainText('Import failed');await expect(page.locator('#html-download')).toBeDisabled();
});
test('superseded File.arrayBuffer cannot overwrite reset or newer import; imported cells start unselected',async({page})=>{await open(page);await page.evaluate(()=>{const original=File.prototype.arrayBuffer;File.prototype.arrayBuffer=function(){const value=original.call(this);return this.name==='slow.ipynb'?new Promise(r=>setTimeout(async()=>r(await value),650)):value;};});const altered=structuredClone(demo);altered.cells[0].id='slow-marker';await page.locator('#file').setInputFiles({name:'slow.ipynb',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(altered))});await page.locator('#reset').click();await page.waitForTimeout(800);await expect(page.locator('[data-id="slow-marker"]')).toHaveCount(0);await ready(page);
 altered.cells[0].id='newest-marker';await page.locator('#file').setInputFiles({name:'newest.ipynb',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(altered))});await expect(page.locator('[data-id="newest-marker"]')).toHaveCount(1);await expect(page.locator('#build')).toBeDisabled();await expect(page.locator('#cells input:checked')).toHaveCount(0);await page.locator('[data-id="nested-python"]').check();await expect(page.locator('#build')).toBeEnabled();
});
test('worker startup failure is visible and cannot enable export',async({page})=>{await page.addInitScript(()=>{window.Worker=class{constructor(){throw new Error('fixture unavailable');}};});await page.goto(appURL);await expect(page.locator('#status')).toContainText('Worker');await expect(page.locator('#build')).toBeDisabled();await expect(page.locator('#html-download')).toBeDisabled();});
