import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {parseNotebook,buildArtifacts,LIMITS} from '../src/engine.mjs';
const fixture=JSON.parse(fs.readFileSync('fixtures/synthetic.ipynb','utf8'));
const copy=()=>structuredClone(fixture);const parse=x=>parseNotebook(JSON.stringify(x));
const ids=['nested-python','tabs-python','long-python'];
test('original ordering, exact text/IDs, empty outputs, safe metadata',()=>{const model=parse(fixture),result=buildArtifacts(model,[...ids].reverse()),out=JSON.parse(result.notebook);assert.deepEqual(out.cells.map(c=>c.id),ids);for(const c of out.cells){const origin=fixture.cells.find(x=>x.id===c.id);assert.equal(c.source,Array.isArray(origin.source)?origin.source.join(''):origin.source);assert.deepEqual(c.outputs,[]);assert.deepEqual(c.metadata,{});assert.equal(c.execution_count,null);}assert.deepEqual(out.metadata,{language_info:{name:'python'}});});
test('all unselected cells and outputs/metadata are absent from raw artifacts',()=>{const r=buildArtifacts(parse(fixture),ids);for(const marker of ['UNSELECTED_','OUTPUT_','METADATA_MUST_NOT_SHIP','MARKDOWN_MUST_NOT_SHIP']){assert.ok(!r.html.includes(marker));assert.ok(!r.notebook.includes(marker));}assert.ok(!/<script\b/i.test(r.html));assert.ok(r.html.includes('&lt;script&gt;'));});
test('NBSP, CRLF, tabs, combining and astral characters survive',()=>{const r=buildArtifacts(parse(fixture),['tabs-python']);assert.ok(r.html.includes(' '));assert.ok(r.html.includes('é'));assert.ok(r.html.includes('😀'));assert.ok(r.html.includes('&#13;\n'));assert.ok(r.html.includes('\t'));assert.equal(JSON.parse(r.notebook).cells[0].source,fixture.cells[3].source);});
test('unknown language is plain text and arbitrary language metadata is discarded',()=>{const f=copy();f.metadata.language_info.name='PRIVATE_LANGUAGE_SENTINEL';const r=buildArtifacts(parse(f),['nested-python']);assert.ok(!r.html.includes('class="token'));assert.ok(!r.notebook.includes('PRIVATE_LANGUAGE_SENTINEL'));assert.deepEqual(JSON.parse(r.notebook).metadata,{});});
for(const [name,mutate] of [
 ['duplicate IDs',f=>f.cells[3].id=f.cells[2].id],['bad ID',f=>f.cells[3].id='<img>'],['missing v4.5 ID',f=>delete f.cells[2].id],['invalid source',f=>f.cells[2].source=[2]],['invalid output shape',f=>f.cells[2].outputs=[{output_type:'bad'}]],['invalid execution count',f=>f.cells[2].execution_count='x'],['invalid metadata',f=>f.metadata=[]],['invalid cell type',f=>f.cells[2].cell_type='heading'],['unsupported minor',f=>f.nbformat_minor=6],['unsupported major',f=>f.nbformat=3],['too many cells',f=>f.cells=Array(1001).fill(f.cells[0])],['NUL source',f=>f.cells[2].source='\0'],['unpaired surrogate source',f=>f.cells[2].source='\ud800']])test(`reject ${name}`,()=>{const f=copy();mutate(f);assert.throws(()=>parse(f));});
test('malformed JSON fails without echo',()=>assert.throws(()=>parseNotebook('{SECRET-MARKER'),e=>e.message==='invalid-json'));
test('raw byte and tree limits fail closed',()=>{assert.throws(()=>parseNotebook(' '.repeat(LIMITS.bytes+1)),/file-limit/);const f=copy();let o=f.metadata;for(let i=0;i<42;i++)o=o.nested={};assert.throws(()=>parse(f),/structure-limit/);});
test('legacy notebooks receive bounded unique IDs, existing IDs kept',()=>{const f=copy();f.nbformat_minor=4;for(const c of f.cells)delete c.id;const m=parse(f);assert.ok(m.cells.every(c=>c.generated&&c.id.length<=64));assert.equal(new Set(m.cells.map(c=>c.id)).size,m.cells.length);});
test('legacy collision allocation remains within schema limit',()=>{const f={nbformat:4,nbformat_minor:4,metadata:{},cells:[{cell_type:'code',metadata:{},execution_count:null,outputs:[],source:''}]};for(let i=0;i<75;i++)f.cells.push({...f.cells[0],id:`cellprint-1-${i}`});/* legacy schema forbids IDs, so malformed mixed-version input is rejected */assert.throws(()=>parse(f));});
test('empty, repeated, unknown, excessive and oversized selections fail',()=>{const m=parse(fixture);for(const a of [[],['nested-python','nested-python'],['missing'],Array(33).fill('x')])assert.throws(()=>buildArtifacts(m,a));const f=copy();f.cells[2].source='x'.repeat(200001);assert.throws(()=>buildArtifacts(parse(f),['nested-python']),/character-limit/);});
test('Unicode codepoints counted without splitting astral characters',()=>{const f=copy();f.cells[2].source='😀'.repeat(200000);assert.equal(parse(f).cells.find(c=>c.id==='nested-python').characters,200000);});
